// Yhistu-frontend-react/src/components/Meter.tsx
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { IMeter } from "../domain/IMeter";
import { AssociationService } from "../services/AssociationService";
import { MeterService } from "../services/MeterService";
import { MeterReadingService } from "../services/MeterReadingService";
import { IMeterReading } from "../domain/IMeterReading";
import meterReading from "./MeterReading";

interface props {
  meter: IMeter;
  updateReadings: any;
}

const Meter = (data: props) => {
  const meterService = new MeterService();
  const meterReadingService = new MeterReadingService();

  const meter = data.meter;
  const [meterReadings, setMeterReadings] = useState([] as IMeterReading[]);

  const [readingData, setReadingData] = useState({
    value: "",
  });

  const [errorMessages, setErrorMessages] = useState(
    [] as string[] | undefined
  );

  const addReading = async (e: Event) => {
    const res = await meterReadingService.add({
      meterId: meter.id!,
      value: parseInt(readingData.value),
      date: new Date().toDateString(),
      autoGenerated: false,
    });
    if (res.status >= 300) {
      setErrorMessages(res.errorMessage);
      console.log(res);
    } else {
      setErrorMessages(undefined);
      data.updateReadings();
    }
  };

  const loadMeterReadings = async () => {
    const meterReadings = await meterReadingService.getAll(meter.id);
    setMeterReadings(meterReadings);
  };

  useEffect(() => {
    loadMeterReadings();
  }, []);

  return (
    <>
      {errorMessages?.map((each) => (
        <div
          className="text-danger validation-summary-errors mt-3 text-center"
          data-valmsg-summary="true"
          data-valmsg-replace="true"
        >
          <ul key={each}>
            <li>{each}</li>
          </ul>
        </div>
      ))}
      <div className="container d-flex justify-content-center mb-3 h-100">
        <div className="col-8 h-100">
          <div className="card h-100 border-secondary justify-content-center">
            <div className="card-body">
              <h3 className="card-title text-center mb-1">
                {meter.meterType?.name}
              </h3>
              <div className="text-center mb-1">
                <small>({meter.meterNumber})</small>
              </div>
              <div className="row align-items-center justify-content-center">
                <div className="form-floating col-auto">
                  <input
                    value={readingData.value}
                    onChange={(e) =>
                      setReadingData({
                        ...readingData,
                        value: e.target.value,
                      })
                    }
                    className="form-control"
                    type="number"
                  />
                  <label>Reading</label>
                </div>
                <div className="col-auto">
                  <h5>{meter.meterType?.measuringUnit?.symbol}</h5>
                </div>
                <div className="col-auto">
                  <input
                    onClick={(e) => addReading(e.nativeEvent)}
                    type="submit"
                    value="Add reading"
                    className="btn btn-outline-secondary btn-lg"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Meter;

// Yhistu-frontend-vue/src/components/Meter.vue
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { useMeterStore } from "@/stores/meters";
import { MeterService } from "@/services/MeterService";
import { MeterReadingService } from "@/services/MeterReadingService";
import type { IMeter } from "@/domain/IMeter";

@Options({
  components: {},
  props: {
    meter: Object as () => IMeter,
  },
})
export default class Meter extends Vue {
  meterStore = useMeterStore();
  meterService = new MeterService();
  meterReadingService = new MeterReadingService();
  meter!: IMeter;
  value!: number;

  errorMessage: Array<string> | null | undefined = null;

  mounted() {
    console.log(this.meter.meterReadings?.length);

    if (
      this.meter.meterReadings != null &&
      this.meter.meterReadings.length !== 0
    ) {
      this.value = this.meter.meterReadings[0].value;
    }
  }

  async addReading(): Promise<void> {
    const res = await this.meterReadingService.add({
      meterId: this.meter.id!,
      value: this.value,
      date: new Date().toDateString(),
      autoGenerated: false,
    });

    if (res.status >= 300) {
      this.errorMessage = res.errorMessage;
      console.log(res);
    } else {
      this.errorMessage = null;
      this.meter.meterReadings = await this.meterReadingService.getAll(
        this.meter.id
      );
    }
  }
}
</script>

<template>
  <div
    v-if="errorMessage != null"
    class="text-danger validation-summary-errors mt-3 text-center"
    data-valmsg-summary="true"
    data-valmsg-replace="true"
  >
    <ul v-for="error of errorMessage">
      <li>{{ error }}</li>
    </ul>
  </div>
  <div class="container d-flex justify-content-center mb-3 h-100">
    <div class="col-8 h-100">
      <div class="card h-100 border-secondary justify-content-center">
        <div class="card-body">
          <h3 class="card-title text-center mb-1">
            {{ meter?.meterType?.name }}
          </h3>
          <div class="text-center mb-1">
            <small>({{ meter?.meterNumber }})</small>
          </div>
          <div class="row align-items-center justify-content-center">
            <div class="form-floating col-auto">
              <input v-model="value" class="form-control" type="number" />
              <label>Reading</label>
            </div>
            <div class="col-auto">
              <h5>{{ meter.meterType?.measuringUnit?.symbol }}</h5>
            </div>
            <div class="col-auto">
              <input
                @click="addReading()"
                type="submit"
                value="Add reading"
                class="btn btn-outline-secondary btn-lg"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
