// Yhistu-frontend-react/src/components/account/Login.tsx
import React, { useContext, useEffect, useState } from "react";
import { IdentityService } from "../../services/IdentityService";
import { AssociationService } from "../../services/AssociationService";
import { ApartmentService } from "../../services/ApartmentService";
import { useNavigate } from "react-router-dom";
import { UserContext } from "../../state/UserContext";
import { IJWTResponse } from "../../domain/IJWTResponse";

const Login = () => {
  const userState = useContext(UserContext);
  const associationService = new AssociationService();
  const identityService = new IdentityService();
  const apartmentService = new ApartmentService();
  const navigate = useNavigate();

  const [loginData, setLoginData] = useState({
    email: "",
    password: "",
  });

  const [errorMessages, setErrorMessages] = useState(
    [] as string[] | undefined
  );

  const loginClicked = async (e: Event) => {
    e.preventDefault();
    if (loginData.email.length > 0 && loginData.password.length > 0) {
      const res = await identityService.login(
        loginData.email,
        loginData.password
      );

      if (res.status >= 300) {
        setErrorMessages(res.errorMessage);
        console.log(res);
      } else {
        userState.setJwt(res.data);
        navigate("/association");
      }
    }
  };

  return (
    <div className="container">
      <main role="main" className="pb-3">
        <h1 className="mb-5 mt-5 text-center">Login</h1>

        <div className="row d-flex justify-content-center">
          <div className="col-md-8">
            {errorMessages?.map((each) => (
              <div
                className="text-danger validation-summary-errors"
                data-valmsg-summary="true"
                data-valmsg-replace="true"
              >
                <ul key={each}>
                  <li>{each}</li>
                </ul>
              </div>
            ))}
            <div>
              <div className="form-floating mb-3">
                <input
                  value={loginData.email}
                  onChange={(e) =>
                    setLoginData({ ...loginData, email: e.target.value })
                  }
                  className="form-control"
                  type="email"
                />
                <label>Email</label>
              </div>
              <div className="form-floating mb-3">
                <input
                  value={loginData.password}
                  onChange={(e) =>
                    setLoginData({ ...loginData, password: e.target.value })
                  }
                  className="form-control"
                  type="password"
                />
                <label>Password</label>
              </div>
              <div className="form-floating mb-3">
                <input
                  onClick={(e) => loginClicked(e.nativeEvent)}
                  type="submit"
                  value="Login"
                  className="btn btn-primary btn-lg"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
export default Login;

// Yhistu-frontend-vue/src/views/identity/Login.vue
<script lang="ts">
import { Vue } from "vue-class-component";
import { useIdentityStore } from "@/stores/identity";
import { IdentityService } from "@/services/IdentityService";
import router from "@/router";

export default class Login extends Vue {
  email = "";
  password = "";
  errorMessage: Array<string> | null | undefined = null;

  identityStore = useIdentityStore();
  identityService = new IdentityService();

  async loginClicked(): Promise<void> {
    console.log("login button clicked");

    if (this.email.length > 0 && this.password.length > 0) {
      const res = await this.identityService.login(this.email, this.password);

      if (res.status >= 300) {
        this.errorMessage = res.errorMessage;
        console.log(res);
      } else {
        this.identityStore.$state.jwt = res.data;
      }
    }
    await router.push("/association");
  }
}
</script>

<template>
  <div class="container">
    <main role="main" class="pb-3">
      <h1 class="mb-5 mt-5 text-center">Login</h1>

      <div class="row d-flex justify-content-center">
        <div class="col-md-8">
          <div
            v-if="errorMessage != null"
            class="text-danger validation-summary-errors"
            data-valmsg-summary="true"
            data-valmsg-replace="true"
          >
            <ul v-for="error of errorMessage" :key="error">
              <li>{{ error }}</li>
            </ul>
          </div>
          <div>
            <div class="form-floating mb-3">
              <input v-model="email" class="form-control" type="email" />
              <label>Email</label>
            </div>
            <div class="form-floating mb-3">
              <input v-model="password" class="form-control" type="password" />
              <label>Password</label>
            </div>
            <div class="form-floating mb-3">
              <input
                @click="loginClicked()"
                type="submit"
                value="Login"
                class="btn btn-primary btn-lg"
              />
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>
